@startwbs

title 3d magnetic library directory tree

* sensors (root folder)

** Makefile

** config
' *** cmake
' *** devops
' *** make
*** src

** doc
' *** doxygen
*** plantuml
**** diagrams
***** out
' *** readTheDocs

** examples
*** arduino
*** mtb
**** psoc
**** xmc

** src
*** framework
**** arduino
**** mtb
***** psoc
***** xmc

*** interfaces
**** c
**** cpp

*** sensors

**** sensors_types.h
**** sensors_common_defines.h
**** sensors_common.h
**** sensors_common.c

**** sensors_gen_1
***** sensors_gen_1_common_defines.h
***** sensors_gen_1_common.h
***** sensors_gen_1_common.c
***** TLx493D_A1B6
****** sensors_TLx493D_A1B6_defines.h
****** sensors_TLx493D_A1B6.h
****** sensors_TLx493D_A1B6.c

**** sensors_gen_2
***** sensors_gen_2_common_defines.h
***** sensors_gen_2_common.h
***** sensors_gen_2_common.c
***** TLE493D_A2B6
****** sensors_TLE493D_A2B6_defines.h
****** sensors_TLE493D_A2B6.h
****** sensors_TLE493D_A2B6.c
***** TLE493D_A2BW
****** sensors_TLE493D_A2BW_defines.h
****** sensors_TLE493D_A2BW.h
****** sensors_TLE493D_A2BW.c
***** TLE493D_P2B6
****** sensors_TLE493D_P2B6_defines.h
****** sensors_TLE493D_P2B6.h
****** sensors_TLE493D_P2B6.c
***** TLE493D_W2B6
****** sensors_TLE493D_W2B6_defines.h
****** sensors_TLE493D_W2B6.h
****** sensors_TLE493D_W2B6.c

**** sensors_gen_3
***** sensors_gen_3_common_defines.h
***** sensors_gen_3_common.h
***** sensors_gen_3_common.c
***** TLE493D_P3B6
****** sensors_TLE493D_P3B6_defines.h
****** sensors_TLE493D_P3B6.h
****** sensors_TLE493D_P3B6.c
***** TLE493D_P3I8
****** sensors_TLE493D_P3I8_defines.h
****** sensors_TLE493D_P3I8.h
****** sensors_TLE493D_P3I8.c

** test
'*** unit "test on build platform"
*** unit "unit testing using Unity"
**** shared
***** Unity "Unity sources"
**** interfaces
***** c
***** cpp
**** frameworks
***** arduino
***** mtb
****** xmc
****** psoc6
**** sensors
***** common
****** gen_1
****** gen_2
****** gen_3
***** TLE493D_A2B6
****** TLE493D_A2B6_arduino.c "includes TLE493D_A2B6_frameworkIndependentCode.c"
****** TLE493D_A2B6_frameworkIndependentCode.c
***** TLE493D_W2B6
***** TLE493D_A2B6


@endwbs
