@startuml

database "<u>raspberrypi-capsense-host</u>\n\ndefines the RPi interface to the capsense_host communication library" as raspberrypi-capsense-host  {
  folder src {
    folder pal {
      file capsense_rpi_pal_i2c.h
    }

    folder platforms {
      folder rpi_hat {
        file capsense_generated_files.h
        file capsense_plaft_conf.h
       file capsense_plaft_conf.c
      }
    }

    file capsense_rpi.hpp
    file capsense_rpi.cpp
    file capsense_rpi_platf.h
  }
}

database "<u>capsense-host</u>\n\ndefines the generic communication library"" as capsense-host  {
  folder "src" as src2 {
    file capsense.h
    file capsense.c
    file capsense_types.h
  }
}

@enduml
