@startmindmap
* Root CMakeLists.txt
** Load psoc4 macros (psoc4.cmake)
**: psoc4_add_tools( VERSION 2.4 ) 
    - Load ModusToolbox tool paths for the given version and
      dependent on the OS used
          CY_TOOLS_PATHS
          CY_TOOL_CFG_BACKEND_CLI
          CY_TOOL_CAPSENSE_CLI
          CY_TOOL_LIN_CLI
          CY_MCUELFTOOL
          CY_OPENOCD_BIN
          CY_OPENOCD_SCRIPTS ;
**: psoc4_configure_toolchain()
    - Configure toolchain variable TOOLCHAIN (default value GCC)
    - Toolchain specific cmake file is loaded
          ${CMAKE_CURRENT_SOURCE_DIR}/toolchain/${TOOLCHAIN}.cmake ;
***: - Sets target platform to ARM
     - Sets GCC tool chain paths
     - Sets compiler, linker, ... flags
     - Sets TOOLCHAIN_* and MTB_TOOLCHAIN variables for use in cmake
**: project( psoc4 C CXX ASM )
   - Define project name, set enabled languages ;
** set CXX vars related to the standard to be used and extensions
**: psoc4_configure_bsp()
   - Check if target BSP variable TARGET is set
   - Load ${CMAKE_CURRENT_SOURCE_DIR}/bsp/${TARGET}.cmake
   - psoc4_load_bsp( NAME ... VERSION ... )
   - psoc4_set_device( ... )
   - psoc4_set_core( ... )
   - Sets BSP_SOURCES and BSP_LINK_LIBRARIES variables
   - add_definitions( -DCY_USING_HAL )
   - psoc4_add_component( BSP_DESIGN_MODUS )
   - psoc4_add_component( CAT2 )
   - psoc4_add_component( PSOC4HAL )
   - psoc4_add_bsp_startup( ... ... )
   - Adds bsp library from BSP_SOURCES and related target link libraries
   - psoc4_add_bsp_design_modus( ${BSP_DIR}/COMPONENT_BSP_DESIGN_MODUS/design.modus )
   - psoc4_add_bsp_design_capsense( ${BSP_DIR}/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense )
;
**: Include libraries
    - lib/cmsis.cmake, 
    - lib/core-lib.cmake
    - lib/mtb-pdl-cat2.cmake
    - lib/mtb-hal-cat2.cmake
    - lib/retarget-io.cmake
    - lib/capsense.cmake
    - lib/lin.cmake ;
**: psoc4_configure_os()
    - Check if variable OS for target OS is set
    - Load OS-specific cmake file ${CMAKE_SOURCE_DIR}/os/${_os}.cmake ;
@endmindmap
