@startuml
scale 400 width

caption \n<b>Figure: Host states for write ops</b>

state writeRequest <<choice>>
state "wait for user request" as waitForRequest
state "send ONE_SCAN command" as sendOneScan
state "send WRITE commands" as writeCMD
state "wait until complete bit set" as ready
state "wait until complete bit set" as checkCompleteBit
state "send RESTART command" as restart
state "receive data" as receiveData

receiveData : asynchronously

[*] -> waitForRequest : init
[*] -> receiveData : init
waitForRequest --> waitForRequest

waitForRequest -> writeRequest : write

writeRequest --> [*] : tuner\nnot "running"

writeRequest --> sendOneScan : tuner\n"running"

sendOneScan --> ready : done

ready --> writeCMD : complete bit set
receiveData -[dashed]-> ready : check received data
receiveData -[dashed]-> checkCompleteBit : check received data
ready --> ready : complete\nbit set?
ready --> sendOneScan : timeout

receiveData --> receiveData #orange : polling
writeCMD --> writeCMD : multiple\nwrites

writeCMD --> restart : done

restart --> checkCompleteBit : done

checkCompleteBit --> checkCompleteBit : complete\nbit set?
checkCompleteBit --> waitForRequest : complete bit set
checkCompleteBit --> restart : timeout

@enduml
