@startuml

!include <c4/C4_Context.puml>  

'ref http://plantuml.com/stdlib

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

title Micropython / Zephyr / PSoC project context

System(userProject, "User projects", "Arbitrary user projects")

System(myPy, "micropython", "Provides micropython interpreter for many boards")
System(zephyr, "Zephyr RTOS", "Provides common hardware interface for many boards")

System(PSoC, "PSoC", "Provides board specific BSPs, code, makefiles, ...")

AddRelTag("up2myPy", $textColor="green", $lineColor="green")
AddRelTag("myPy2zephyr", $textColor="green", $lineColor="green")
AddRelTag("zephyr2PSoC", $textColor="red", $lineColor="red")
'AddRelTag("up2zephyr", $textColor="red", $lineColor="red")
'AddRelTag("myPy2PSoC", $textColor="red", $lineColor="red")

Rel(userProject, myPy, "Employ", "project scope", $tags="up2myPy")
'Rel(userProject, zephyr, "Use", "out of scope", $tags="up2zephyr")
Rel(myPy, zephyr, "Use board specifics through Zephyr", "project scope", $tags="myPy2zephyr" )
'Rel(myPy, PSoC, "Directly use board specifics", "out of scope", $tags="myPy2PSoC")
Rel(zephyr, PSoC, "Use board specifics", "uses ifyall port", $tags="zephyr2PSoC")

@enduml
